# Generated by Django 2.1.2 on 2019-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.CharField(default='-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
