# Generated by Django 2.1.4 on 2019-01-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190106_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
    ]
