# Generated by Django 2.1.2 on 2019-01-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellation',
            name='txHash',
            field=models.CharField(max_length=70),
        ),
    ]
