# Generated by Django 2.1.4 on 2019-01-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190124_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
