# Generated by Django 2.1.4 on 2019-01-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstat',
            name='location',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
