# Generated by Django 2.1.4 on 2019-01-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190104_1607'),
        ('operate', '0003_chartstat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstat',
            name='tx_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Cancellation'),
        ),
    ]
